name: Deploy on On-prem

on:
  push:
    branches: [setup-deployment-pipeline]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Deploy to On-prem
      run: |
            sshpass -p "${{ secrets.SSH_PASS }}" ssh -tt -i ~/.ssh/id_rsa "${{secrets.SSH_USER_NAME}}"@"${{secrets.SSH_HOST_IP}}" << EOF
              cd /home/zeropixels/Documents/dev/CRAFT2.0
              git pull origin main
              cd craft-backend
              npm ci
              pm2 reload craft_backend --update-env
              cd ../craft-frontend
              npm ci
              pm2 reload craft_frontend --update-env && pm2 save && exit
            EOF